name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.5.4'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Unit Test
        run: python test.py
      - name: Send Status Email
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: hops.aiml.github@gmail.com
          password: hops@123
          subject: Github Actions job result for ${{github.repository}}
          body: Build job of ${{github.repository}} completed with status ${{job.status}}!
          to: vivek@hops.healthcare, bpc999@gmail.com
          from: Hops GitHub Worflow